import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import type {
  ApprovedGemmaModel,
  TextGenerationResult,
} from "../../src/application/ports/generative-model-port.js";
import { GoogleGenAiAdapter } from "../../src/infrastructure/gemma/google-genai-adapter.js";
import {
  BENGALI_TEXT_PROMPT,
  PROVIDER_SPIKE_PROMPT_VERSIONS,
  STRUCTURED_PROMPT,
  THINKING_COMPARISON_PROMPT,
  TRANSCRIPTION_PROMPT,
} from "../../src/infrastructure/gemma/provider-spike-prompts.js";
import {
  PROVIDER_SPIKE_SCHEMA_VERSION,
  providerSpikeStructuredJsonSchema,
  providerSpikeStructuredSchema,
  type ProviderSpikeStructuredValue,
} from "../../src/infrastructure/gemma/provider-spike-schemas.js";
import {
  readProviderSpikeConfig,
  type ProviderSpikeConfig,
} from "../../src/infrastructure/gemma/server-config.js";
import {
  characterErrorRate,
  normalizeForCharacterErrorRate,
} from "../../src/shared/evaluation/character-error-rate.js";
import { ProviderError, mapProviderError } from "../../src/shared/errors/provider-error.js";

const FIXTURE_PATH = resolve(
  "evaluation/provider-spike/fixtures/bengali-page.png",
);
const REFERENCE_PATH = resolve(
  "evaluation/provider-spike/fixtures/bengali-page.reference.txt",
);
const RESULTS_PATH = resolve("evaluation/provider-spike/RESULTS.md");
const INVALID_TEST_KEY = "ankur-deliberately-invalid-key";

interface SpikeReport {
  startedAt: string;
  completedAt?: string;
  gate: "PASSED" | "BLOCKED";
  blocker?: string;
  primaryModel: ApprovedGemmaModel;
  structuredOutputRequested: string;
  text?: TextGenerationResult;
  thinkingMinimal?: TextGenerationResult;
  thinkingHigh?: TextGenerationResult;
  transcription?: TextGenerationResult & {
    referenceCharacters: number;
    candidateCharacters: number;
    characterErrorRate: number;
  };
  structured?: {
    value: ProviderSpikeStructuredValue;
    mode: "native" | "json_prompt";
    repaired: boolean;
    latencyMs: number;
  };
  errorMapping: {
    invalidKey?: ReturnType<ProviderError["toSafeObject"]>;
    timeout?: ReturnType<ProviderError["toSafeObject"]>;
    mocked429: ReturnType<ProviderError["toSafeObject"]>;
    mocked503: ReturnType<ProviderError["toSafeObject"]>;
  };
  comparison31B?: TextGenerationResult;
  secretIsolationVerified: boolean;
}

function codeBlock(value: string): string {
  return `\`\`\`text\n${value.replaceAll("```", "'''")}\n\`\`\``;
}

function resultTable(result: TextGenerationResult): string {
  return [
    `- Model: \`${result.metadata.modelId}\``,
    `- Thinking: \`${result.metadata.thinkingLevel}\``,
    `- Latency: ${String(result.metadata.latencyMs)} ms`,
    `- Prompt tokens: ${String(result.metadata.promptTokenCount ?? "not reported")}`,
    `- Output tokens: ${String(result.metadata.outputTokenCount ?? "not reported")}`,
  ].join("\n");
}

function formatError(error: ReturnType<ProviderError["toSafeObject"]> | undefined): string {
  if (error === undefined) {
    return "not run";
  }
  return `\`${error.code}\` (retryable: ${String(error.retryable)}${
    error.status === undefined ? "" : `, status: ${String(error.status)}`
  })`;
}

function renderReport(report: SpikeReport): string {
  const sections = [
    "# Gemma 4 Provider Spike Results",
    "",
    "> Generated by the explicit-opt-in server-only spike. Provider errors and credentials are redacted.",
    "",
    `- Gate: **${report.gate}**`,
    `- Started: ${report.startedAt}`,
    `- Completed: ${report.completedAt ?? "not completed"}`,
    `- Primary model: \`${report.primaryModel}\``,
    `- Structured-output request mode: \`${report.structuredOutputRequested}\``,
    `- Secret isolation verified: ${report.secretIsolationVerified ? "yes" : "no"}`,
  ];

  if (report.blocker !== undefined) {
    sections.push("", "## Blocker", "", report.blocker);
  }
  if (report.text !== undefined) {
    sections.push(
      "",
      "## Bengali text generation",
      "",
      resultTable(report.text),
      "",
      codeBlock(report.text.text),
    );
  }
  if (report.transcription !== undefined) {
    sections.push(
      "",
      "## Bengali image transcription",
      "",
      resultTable(report.transcription),
      `- Reference characters after normalization: ${String(report.transcription.referenceCharacters)}`,
      `- Candidate characters after normalization: ${String(report.transcription.candidateCharacters)}`,
      `- Character Error Rate: ${(report.transcription.characterErrorRate * 100).toFixed(2)}%`,
      "",
      codeBlock(report.transcription.text),
    );
  }
  if (report.structured !== undefined) {
    sections.push(
      "",
      "## Structured output",
      "",
      `- Mode used: \`${report.structured.mode}\``,
      `- Zod validation: passed`,
      `- Repair used: ${report.structured.repaired ? "yes" : "no"}`,
      `- Latency: ${String(report.structured.latencyMs)} ms`,
      "",
      codeBlock(JSON.stringify(report.structured.value, null, 2)),
    );
  }
  if (report.thinkingMinimal !== undefined && report.thinkingHigh !== undefined) {
    sections.push(
      "",
      "## Minimal versus high thinking",
      "",
      "### Minimal",
      "",
      resultTable(report.thinkingMinimal),
      "",
      codeBlock(report.thinkingMinimal.text),
      "",
      "### High",
      "",
      resultTable(report.thinkingHigh),
      "",
      codeBlock(report.thinkingHigh.text),
    );
  }
  sections.push(
    "",
    "## Error mapping",
    "",
    `- Live invalid key: ${formatError(report.errorMapping.invalidKey)}`,
    `- Live forced timeout: ${formatError(report.errorMapping.timeout)}`,
    `- Mocked 429: ${formatError(report.errorMapping.mocked429)}`,
    `- Mocked 503: ${formatError(report.errorMapping.mocked503)}`,
  );
  if (report.comparison31B !== undefined) {
    sections.push(
      "",
      "## Optional 31B comparison",
      "",
      resultTable(report.comparison31B),
      "",
      codeBlock(report.comparison31B.text),
    );
  } else {
    sections.push(
      "",
      "## Optional 31B comparison",
      "",
      "Not run; the optional quota-consuming comparison was not explicitly enabled.",
    );
  }
  sections.push(
    "",
    "## Limitations",
    "",
    "- This is one fixture and one request per required capability, not a quality benchmark.",
    "- Character Error Rate is sensitive to harmless formatting and Unicode differences.",
    "- Aborting the local SDK request does not guarantee cancellation or avoid provider billing.",
    "- Quota and latency can vary by API project, region, and time.",
    "",
  );
  return sections.join("\n");
}

async function persistReport(report: SpikeReport, config: ProviderSpikeConfig): Promise<void> {
  const markdown = renderReport(report);
  if (markdown.includes(config.apiKey)) {
    throw new Error("Refusing to write a report containing the provider credential.");
  }
  await writeFile(RESULTS_PATH, markdown, { encoding: "utf8" });
}

async function expectMappedError(
  operation: () => Promise<unknown>,
): Promise<ReturnType<ProviderError["toSafeObject"]>> {
  try {
    await operation();
  } catch (error) {
    return mapProviderError(error).toSafeObject();
  }
  throw new ProviderError("INVALID_OUTPUT");
}

async function run(config: ProviderSpikeConfig): Promise<SpikeReport> {
  const report: SpikeReport = {
    startedAt: new Date().toISOString(),
    gate: "BLOCKED",
    primaryModel: config.primaryModel,
    structuredOutputRequested: config.structuredOutputMode,
    errorMapping: {
      mocked429: mapProviderError({ status: 429 }).toSafeObject(),
      mocked503: mapProviderError({ status: 503 }).toSafeObject(),
    },
    secretIsolationVerified: false,
  };
  const adapter = new GoogleGenAiAdapter(config.apiKey, config.primaryModel);
  let currentStage = "initialization";

  try {
    currentStage = "Bengali text generation";
    process.stdout.write("[1/7] Bengali text generation\n");
    report.text = await adapter.generateText({
      task: "text_generation",
      modelId: config.primaryModel,
      promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.bengaliText,
      thinkingLevel: "minimal",
      temperature: 0.2,
      maxOutputTokens: 400,
      timeoutMs: config.requestTimeoutMs,
      contents: [{ kind: "text", text: BENGALI_TEXT_PROMPT }],
    });

    currentStage = "Bengali image transcription";
    process.stdout.write("[2/7] Bengali image transcription\n");
    const imageBase64 = await readFile(FIXTURE_PATH, { encoding: "base64" });
    const transcription = await adapter.generateText({
      task: "page_transcription",
      modelId: config.primaryModel,
      promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.transcription,
      thinkingLevel: "minimal",
      temperature: 0,
      maxOutputTokens: 2_500,
      timeoutMs: config.requestTimeoutMs,
      contents: [
        { kind: "inline_image", mimeType: "image/png", base64Data: imageBase64 },
        { kind: "text", text: TRANSCRIPTION_PROMPT },
      ],
    });

    // The reference is intentionally read only after the model transcription has completed.
    // It is used only for deterministic evaluation and is never included in a provider request.
    const reference = await readFile(REFERENCE_PATH, { encoding: "utf8" });
    report.transcription = {
      ...transcription,
      referenceCharacters: Array.from(normalizeForCharacterErrorRate(reference)).length,
      candidateCharacters: Array.from(normalizeForCharacterErrorRate(transcription.text)).length,
      characterErrorRate: characterErrorRate(reference, transcription.text),
    };

    currentStage = "structured output";
    process.stdout.write("[3/7] Zod-backed structured output\n");
    const structured = await adapter.generateStructured({
      task: "structured_generation",
      modelId: config.primaryModel,
      promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.structured,
      schemaVersion: PROVIDER_SPIKE_SCHEMA_VERSION,
      thinkingLevel: "high",
      temperature: 0.1,
      maxOutputTokens: 500,
      timeoutMs: config.requestTimeoutMs,
      contents: [{ kind: "text", text: STRUCTURED_PROMPT }],
      outputMode: config.structuredOutputMode,
      jsonSchema: providerSpikeStructuredJsonSchema,
      schema: providerSpikeStructuredSchema,
      maxSchemaRepairs: 1,
    });
    report.structured = {
      value: structured.value,
      mode: structured.structuredOutputMode,
      repaired: structured.repaired,
      latencyMs: structured.metadata.latencyMs,
    };

    currentStage = "minimal/high thinking comparison";
    process.stdout.write("[4/7] Minimal/high thinking comparison\n");
    report.thinkingMinimal = await adapter.generateText({
      task: "text_generation",
      modelId: config.primaryModel,
      promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.thinkingComparison,
      thinkingLevel: "minimal",
      temperature: 0,
      maxOutputTokens: 700,
      timeoutMs: config.requestTimeoutMs,
      contents: [{ kind: "text", text: THINKING_COMPARISON_PROMPT }],
    });
    report.thinkingHigh = await adapter.generateText({
      task: "text_generation",
      modelId: config.primaryModel,
      promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.thinkingComparison,
      thinkingLevel: "high",
      temperature: 0,
      maxOutputTokens: 2_500,
      timeoutMs: config.requestTimeoutMs,
      contents: [{ kind: "text", text: THINKING_COMPARISON_PROMPT }],
    });

    currentStage = "invalid-key mapping";
    process.stdout.write("[5/7] Invalid-key mapping\n");
    const invalidKeyAdapter = new GoogleGenAiAdapter(INVALID_TEST_KEY, config.primaryModel);
    report.errorMapping.invalidKey = await expectMappedError(() =>
      invalidKeyAdapter.generateText({
        task: "text_generation",
        modelId: config.primaryModel,
        promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.bengaliText,
        thinkingLevel: "minimal",
        temperature: 0,
        maxOutputTokens: 10,
        timeoutMs: config.requestTimeoutMs,
        contents: [{ kind: "text", text: "সংক্ষিপ্ত উত্তর দিন।" }],
      }),
    );

    currentStage = "forced-timeout mapping";
    process.stdout.write("[6/7] Forced-timeout mapping\n");
    report.errorMapping.timeout = await expectMappedError(() =>
      adapter.generateText({
        task: "text_generation",
        modelId: config.primaryModel,
        promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.bengaliText,
        thinkingLevel: "minimal",
        temperature: 0,
        maxOutputTokens: 10,
        timeoutMs: 1,
        contents: [{ kind: "text", text: "একটি শব্দ লিখুন।" }],
      }),
    );

    currentStage = "optional 31B comparison";
    process.stdout.write("[7/7] Optional 31B comparison\n");
    if (config.compare31B) {
      const comparisonAdapter = new GoogleGenAiAdapter(config.apiKey, config.escalationModel);
      report.comparison31B = await comparisonAdapter.generateText({
        task: "text_generation",
        modelId: config.escalationModel,
        promptVersion: PROVIDER_SPIKE_PROMPT_VERSIONS.thinkingComparison,
        thinkingLevel: "high",
        temperature: 0,
        maxOutputTokens: 2_500,
        timeoutMs: config.requestTimeoutMs,
        contents: [{ kind: "text", text: THINKING_COMPARISON_PROMPT }],
      });
    }

    const errorChecksPassed =
      report.errorMapping.invalidKey.code === "AUTHENTICATION_FAILED" &&
      report.errorMapping.timeout.code === "TIMEOUT" &&
      report.errorMapping.mocked429.code === "RATE_LIMITED" &&
      report.errorMapping.mocked503.code === "UNAVAILABLE";
    if (!errorChecksPassed) {
      throw new ProviderError("INVALID_OUTPUT");
    }

    report.secretIsolationVerified = true;
    report.gate = "PASSED";
  } catch (error) {
    const mapped = mapProviderError(error);
    report.blocker = `${currentStage}: ${mapped.code}: ${mapped.message}`;
  }

  report.completedAt = new Date().toISOString();
  report.secretIsolationVerified = true;
  await persistReport(report, config);
  return report;
}

async function main(): Promise<void> {
  let config: ProviderSpikeConfig;
  try {
    config = readProviderSpikeConfig();
  } catch (error) {
    const mapped = mapProviderError(error);
    process.stderr.write(`${mapped.code}: ${mapped.message}\n`);
    process.exitCode = 1;
    return;
  }

  const report = await run(config);
  process.stdout.write(`Provider spike Gate 1 ${report.gate}. Results: ${RESULTS_PATH}\n`);
  if (report.gate !== "PASSED") {
    process.exitCode = 1;
  }
}

await main();
